# Generated by Django 4.1.7 on 2023-03-16 17:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr_helper", "0003_cv_delete_uploadedfile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CV",
            new_name="Opis",
        ),
    ]
